# Grid Search Test Configuration File - Simplified Version

# Base settings
base:
  dataset_path: "/home/e4user/rag-eval/data/datasets/ragas_testset_tesi.json"
  dir_path: "/home/e4user/rag-eval/data/Grasselli_md"
  output_csv: "/home/e4user/rag-eval/grid_search_test_results.csv"
  r2r_base_url: "http://localhost:7272"
  r2r_timeout: 604800  # 1 week timeout (7*24*60*60 seconds)
  ingestion_thread_pool_workers: 16
  search_thread_pool_workers: 16

# LLM Configuration
llm:
  model: ${LLM_MODEL}
  api_key: ${LLM_API_KEY}
  base_url: ${LLM_API_BASE}

# Embeddings Configuration
embeddings:
  model: ${EMBEDDINGS_MODEL}
  api_key: ${EMBEDDINGS_API_KEY}
  base_url: ${EMBEDDINGS_API_BASE}
  embedding_dimension: 1024

# RAG Generation Configuration
rag_generation:
  model: ${RAG_GENERATION_MODEL}
  api_base: ${RAG_GENERATION_API_BASE}
  api_key: ${RAG_GENERATION_API_KEY}
  temperature: 0.8
  max_tokens: 8192
  stream: false

# Ragas Evaluation Configuration
ragas_evaluation:
  llm_model: ${LLM_MODEL}
  llm_api_key: ${LLM_API_KEY}
  llm_api_base: ${LLM_API_BASE}
  llm_max_tokens: 4096
  llm_temperature: 0.1
  llm_timeout: 240
  llm_top_p: 1
  embeddings_timeout: 240
  embeddings_model: ${EMBEDDINGS_MODEL}
  embeddings_api_key: ${EMBEDDINGS_API_KEY}
  embeddings_api_base: ${EMBEDDINGS_API_BASE}
  eval_timeout: 3600
  cache_dir: "ragas_cache"
  batch_size: 500
  max_workers: ${CPU_COUNT}
  metrics:
    - "faithfulness"
    - "context_precision"
    - "context_recall"

# Hybrid Search Settings
hybrid_search_settings:
  full_text_weight: 0.3
  semantic_weight: 0.7
  full_text_limit: 200
  rrf_k: 60

# Search Configurations - Reduced for testing
search_configs:
  semantic_search:
    search_settings:
      limit: 5
      use_semantic_search: true
      use_hybrid_search: false
      use_fulltext_search: false
    search_mode: "custom"
  
  hybrid_search:
    search_settings:
      use_hybrid_search: true
      use_semantic_search: true
      use_fulltext_search: true
      hybrid_settings:
        full_text_weight: 0.3
        semantic_weight: 0.7
        full_text_limit: 200
        rrf_k: 60
      limit: 5
    search_mode: "custom"

# Chunker Configurations - Reduced for testing
chunkers:
  character:
    type: "CharacterChunker"
    params:
      chunk_size: 1024
      chunk_overlap: 256
  
  semantic:
    type: "SemanticChunker"
    params:
      chunk_size: 256
      threshold: 0.5

# Enrichment Configurations - Reduced for testing
enrichments:
  metadata_enrichment:
    type: "MetadataEnrichment"
    params:
      include_entities: true
      include_keywords: true
      include_topic: true
      max_entities: 15
      max_keywords: 15
      max_concurrency: 32
      show_progress_bar: true
  
  contextual_enrichment:
    type: "ContextualEnrichment"
    params:
      n_chunks: 2
      max_concurrency: 32
      show_progress_bar: true
